### PR TITLE
revert '* as  tweens' import introduced with v6.2 due to vitest tests…

### PR DESCRIPTION
**Pull request by bonev93**
… failing because of the cjs import

I work on a private repository where tests started failing after bumping react-confetti from v6.1 to v6.4.
Turns out the cjs import in Confetti.ts makes vitest fail with an error saying tweenFunction is not a function.
Sorry for not being able to provide codesamples.

### CODE REVIEW

**Comment by alampros** [comment]
Thanks for the PR! Sorry you ran into issues. 

I'd like to check that this doesn't re-export the whole tweens lib when I get time. 

If it does, it might just be easier to yoink that one func out of the lib and include it statically.

**Comment by bonev93** [comment]
@alampros my pleasure - it's a cool library. 

As for the re-export check you would like to make - I checked again and this is the only place within the source code where tween-functions is referenced so yoinking(not a native speaker here so I learned a new word:D) the function and including it statically is an option as well, however I think rollup is doing a tree-shaking on your behalf when "npm run build" script is executed. (see tree-shaking paragraph here https://www.npmjs.com/package/rollup). 

https://bundlephobia.com/package/tween-functions@1.2.0 - gzipped version sits at 885b

let me know if I can help with any changes needed :)

**Comment by alampros** [comment]
Excellent - thanks! Sorry for the delay. I'll try to get this merged today

**Review by alampros — APPROVED** [review]
